# Clase de dimensiones con arreglos de `Numpy`

A continuación se va a trabajar con **escalares.**

In [1]:
# Importación de la biblioteca

import numpy as np

In [2]:
# Creación de un escalar
scalar = np.array(42)
scalar.ndim

0

A continuación se va a trabajar con un **vector**.

In [3]:
# Creación de un vector
vector = np.array([1, 2, 3])
print(vector)
vector.ndim

[1 2 3]


1


Nótese que el vector anterior tiene una dimensión de **uno**.

Ahora, usando una matriz:

In [4]:
matriz = np.array([[1, 2, 3], [4, 5, 6]])
matriz.ndim

2

Nótese que para el caso de la matriz se tiene una dimensión dos. Finalmente, si se considera un tensor:

In [6]:
# Creación de un tensor:
tensor = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
                   [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
                   [[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
print(tensor)
tensor.ndim

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


3

Se puede observar que se trata de tres matrices organizadas dentro de un arreglo a su vez matricial, que es lo que se conoce como tensor. Esto se puede seguir realizando, lo que va a hacer que aumente la dimensión. En todo caso, siempre se denomina esto como *tensor*.

## Agregar o eliminar dimensiones

Consideremos el caso de un vector. Con el parámetro `ndmin` de `np.array` puedo forzar una cantidad de dimensiones mínima.

In [7]:
vector2 = np.array([10, 13, 5], ndmin = 10)
print(vector2)
vector2.ndim

[[[[[[[[[[10 13  5]]]]]]]]]]


10

Ahora bien, si quiero aumentar la dimensión en un eje particular, uso la función `np.expand_dims()`.
- Si quiero aumentar la dimensión a nivel de filas, uso `axis = 0`.
- Si quiero aumentar la dimensión a nivel de columnas, uso `axis = 1`.

In [8]:
expand = np.expand_dims(np.array([9, 12, 5]), axis = 0)
print(expand)
expand.ndim

[[ 9 12  5]]


2

Nótese que se tiene dobles corchetes para abrir y cerrar, lo que corrobora que, en efecto, se tiene una dimensión adicional respecto al *array* inicialmente creado.

Ahora bien, si por el contrario quiero reducir la cantidad de dimensiones que tiene un arreglo, puedo usar la función `np.squeeze()`.

In [9]:
vector3 = np.squeeze(vector2)
print(vector3, vector3.ndim)

[10 13  5] 1


Nótese que se simplificó la cantidad de dimensiones del vector que se creó con dimensión diez a la mínima posible, que es de dimensión uno.