# Creando arreglos en `Numpy`.

In [2]:
import numpy as np

Para generar un arreglo vectorial de números enteros entre ciertas cantidades, se puede usar la función `np.arange(a, b)`, donde $a$ es el número donde comienza la lista y $b$ es el siguiente número entero al que deseo que cierre el arreglo. Por ejemplo, para un arreglo vectorial que comience en uno y tenga diez elementos:

In [6]:
vector_1 = np.arange(1, 10)
vector_1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Nótese que en este caso se ha indicado que el arreglo comience en uno y que finalice en nueve, siendo esto último indicado poniendo como segundo argumento el siguiente número entero que es diez.

Ahora bien, puedo arregar un tercer argumento $c$, es decir, `np.arange(a, b, c)`, donde este indique los saltos que desee que tenga el arreglo. Así, por ejemplo, si qusiera un arreglo de **`Numpy`** con todos los enteros pares entre 2 y 20:

In [8]:
# Números pares entre dos y vente, inclusive
vector_pares = np.arange(2, 21, 2)
vector_pares

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

Semejantemente, con los números impares:

In [9]:
# Números impares entre uno y diecinueve, inclusive:
vector_impares = np.arange(1, 20, 2)
vector_impares

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

También puedo crear un vector con $n$ ceros usando el código:

In [11]:
# Con n = 5
vector_ceros = np.zeros(5)
vector_ceros

array([0., 0., 0., 0., 0.])

Pero si lo que quiero es crear una matriz $n \times m$ de ceros, donde $n= 10$ y $m = 6$, entonces:

In [13]:
matriz_ceros = np.zeros((10, 6))
matriz_ceros

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

Vale la pena notar que la dimensión se debe encasillar con paréntesis. Por otro lado, si se quiere un vector o matriz de unos, se cambia `zeros` por `ones`. Veámoslo con el caso de matrices:

In [14]:
# Matriz 10 x 6 de unos
matriz_unos = np.ones((10, 6))
matriz_unos

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

Ahora bien, supongamos que queremos crear un vector que tenga todos los $n$ números reales entre $a$ y $b$ (inclusive), tales que estos números son equispaciados. Para ello, se usa `np.linspace(a, b, c)`. Entonces, si nosotros queremos tener los números entre uno y diez, y que este vector esté en $\mathbb{R}^{10}$, entonces:

In [16]:
vector_2 = np.linspace(1, 10, 10)
vector_2

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

El caso anterior, claramente, es inusual, pues para crear listas como la anterior se usan las opciones que se describen al comienzo de este *notebook*. Funciones de este estilo tendrán mayor utilidad a la hora de crear mallas. Supongamos, por ejemplo, que queremos un vector que tenga $n = 30$ números reales equiespaciados entre $a = 0$ y $b = 1$.

In [19]:
# 30 números entre cero y uno
vector_3 = np.linspace(0, 1, 30)
vector_3

array([0.        , 0.03448276, 0.06896552, 0.10344828, 0.13793103,
       0.17241379, 0.20689655, 0.24137931, 0.27586207, 0.31034483,
       0.34482759, 0.37931034, 0.4137931 , 0.44827586, 0.48275862,
       0.51724138, 0.55172414, 0.5862069 , 0.62068966, 0.65517241,
       0.68965517, 0.72413793, 0.75862069, 0.79310345, 0.82758621,
       0.86206897, 0.89655172, 0.93103448, 0.96551724, 1.        ])

Por otro lado, si queremos crear la *matriz identidad* de dimensión $n \times n$, entonces se puede usar la función `np.eye(n)`. Por ejemplo, si queremos una matriz identidad $6 \times 6$, entonces:

In [20]:
# Matriz identidad 6 x 6
matriz_identidad = np.eye(6)
matriz_identidad

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

Adicionalmente, si el interés es crear un escalar aleatorio entre cero y uno, se puede usar `np.random.rand()`.

In [21]:
# Escalar aleatorio
np.random.rand()

0.6503675142055848

Pero si se quiere un vector de $\mathbb{R}^{n}$ cuyas entradas sean números aleatorios entre cero y uno, entonces:

In [22]:
# Vector de dimensión cuatro con entradas aleatorias:
np.random.rand(4)

array([0.72111821, 0.81024144, 0.49029905, 0.10781947])

¿Y si queremos que sea una cantidad aleatoria entre $a$ y $b$?

In [23]:
np.random.randint(1, 15)

2

Y para indicarle que quiero que se generen en un arreglo especifico?

In [24]:
np.random.randint(1, 10, (2, 3))

array([[7, 1, 8],
       [5, 5, 1]])