# Atributos `shape` y `reshape` en `Numpy`.

In [1]:
# Lectura de Numpy
import numpy as np

In [6]:
# Creación de un array
matriz = np.random.randint(1, 10, (3, 2))
matriz

array([[3, 3],
       [8, 4],
       [1, 6]])

Nótese que se ha generado un arreglo matricial $3 \times 2$. Con el atributo `shape` de este arreglo podemos conocer esta característica:

In [4]:
matriz.shape

(3, 2)

Sin embargo, yo podría querer que esta matriz se convierta en un vector, el cual debería ser de $\mathbb{R^6}$ teniendo en cuenta que es la cantidad de elementos que tiene `matriz`.

In [7]:
matriz.reshape(1, 6)

array([[3, 3, 8, 4, 1, 6]])

Nótese que estas redimensiones las realiza de izquierda a derecha y luego de arriba a abajo, que es como se hace en el lenguaje de programación `C`. Se puede indicar que se haga esto de forma explítica tomando a `np.reshape()` como función y pasando a `C` como parámetro de la función.

In [8]:
# Indicando de forma explícita que haga el reshape como en C
np.reshape(matriz, (2, 3), 'C')

array([[3, 3, 8],
       [4, 1, 6]])

No obstante, yo podría querer que esta organización la haga de arriba abajo y luego de izquierda a derecha, que es como de realiza en `Fortant`, lo cual se indica usando como parámetro `F`:

In [10]:
# Indicando de forma explícita que haga el reshape como en Fortrant:
np.reshape(matriz, (2, 3), 'F')

array([[3, 1, 4],
       [8, 3, 6]])

Y si simplemente quiero que se lleve a cabo de la forma en que se esté mejor optimizado en mi sistema, paso como parámetro `'A'`.

In [11]:
np.reshape(matriz, (2, 3), 'A')

array([[3, 3, 8],
       [4, 1, 6]])

Nótese que se obtiene el mismo arreglo que cuando se usa el orden de `C`, lo que quiere decir que mi computadora tiene mejor optimizado este lenguaje.