# Funciones principales de `Numpy`.

In [1]:
# Importando la biblioteca
import numpy as np

**`Numpy`** cuenta con decenas de funciones que pueden ser útiles para el trabajo que se realiza como científico de datos.

In [5]:
# Matriz de ejemplo
matriz = np.random.randint(1, 20, (2, 5))
matriz

array([[11, 17, 13,  1,  1],
       [ 7,  1, 15, 11, 18]])

Con las funciones `np.max()` y `np.min()` puedo conocer los números máximo y mínimo respectivamente de un arreglo:

In [10]:
print(matriz.max())
print(matriz.min())

18
1


Ahora, si yo quisiera conocer por ejemplo por columnas, entonces agrego `axis = 0`, o bien, si lo quiero por filas, uso `axis = 1`.

In [11]:
# Máximo por columna
matriz.max(axis = 0)

array([11, 17, 15, 11, 18])

Si yo no quisiera saber como tal cuál es el número máximo, sino su índice, entonces uso `np.argmax()`.

In [13]:
matriz.argmax(1)

array([1, 4], dtype=int64)

Es importante anotar que si el valor máximo tiene una frecuencia mayor a uno, la función `argmax` simplemente retornará el índice del primero que encuentre.

Ahora, si me interesa saber el rango, esto es, la diferencia entre el máximo y el mínimo de un arreglo, entonces puedo usar la función `np.ptp()` (*peak to peak*).

In [17]:
matriz.ptp()

17

Para saber el percentil $n$-ésimo:

In [18]:
# Supongamos n = 25
np.percentile(matriz, q = 25)

2.5

Para ordenar los valores:

In [20]:
matriz.sort()
matriz

array([[ 1,  1, 11, 13, 17],
       [ 1,  7, 11, 15, 18]])