# El copy en `Numpy`.

In [2]:
import numpy as np

In [3]:
arreglo = np.arange(0, 11)
arreglo

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Hagamos un *scling* sobre `arreglo`.

In [5]:
trozo_de_arreglo = arreglo[0:6]
trozo_de_arreglo

array([0, 1, 2, 3, 4, 5])

Supongamos que ahoga quiero cambiar todos los valores de `trozo_de_array` en cero:

In [6]:
trozo_de_arreglo[:] = 0
trozo_de_arreglo

array([0, 0, 0, 0, 0, 0])

¿Qué pasa si revisamos a `arreglo`?

In [7]:
arreglo

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

¡Se cambiaron los valores de `arreglo` a pesar de que he realizado la modificación en `trozo_de_arreglo`. Esto sucede porque este último objeto tiene un puntero en memoria ligado a `arreglo`. Para evitar esto, se puede usar el método `copy`.

In [9]:
copia_arreglo = arreglo.copy()
copia_arreglo

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [10]:
copia_arreglo[:] = 100
copia_arreglo

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [12]:
arreglo

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

¡Y no se modificó a `arreglo`!