# Condiciones en `Numpy`.

In [1]:
import numpy as np

Las condiciones sirven para acceder a elementos particulares de un arreglo cuando un simple *slicing* no lo permite hacer de forma inmediata. Creemos el siguiente arreglo:


In [2]:
arreglo = np.linspace(1, 10, 10, dtype = 'int8')
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

¿Cuáles de los elementos de esta lista son mayores a cinco? Lo podemos declarar explícitamente y nos devolverá un arreglo de *booleanos*.

In [3]:
mayores_cinco = arreglo > 5
mayores_cinco

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

Si queremos obtener de forma explícita los valores que cumplen la condición que hemos definido, basta con introducir el arreglo *booleano* como un *slicing*, y solo nos devolverá los elementos del arreglo que tengan la condición `True`.

In [4]:
arreglo[mayores_cinco]

array([ 6,  7,  8,  9, 10], dtype=int8)

Podemos juntar varias condiciones con los conectores `&` y `|`.

In [6]:
arreglo[(arreglo > 5) & (arreglo < 9)]

array([6, 7, 8], dtype=int8)

También podemos indicarle al arreglo que le asigne un valor particular a aquellos elementos que cumplen con una condición:

In [8]:
arreglo[arreglo % 2 == 0] = '0'
arreglo

array([1, 0, 3, 0, 5, 0, 7, 0, 9, 0], dtype=int8)

Le he pedido que todos los elementos de `arreglo` que sean pares, es decir, que cumplen con la condición de que su módulo sea nulo, sean cambiados por cero. Nótese que, en efecto, `arreglo` solo contiene a números impares y al cero donde anteriormente se situaban valores pares.