# Operaciones en `Numpy`.

In [1]:
import numpy as np

In [2]:
# Creemos una lista tradicional de Python:
lista = [1, 2]
lista

[1, 2]

Si ejecuto el comando `lista * 2`, me va a replicar los elementos de mi lista dos veces.

In [3]:
lista * 2

[1, 2, 1, 2]

Sin embargo, esto no ocurre en `Numpy`, pues de forma similar a como sucede con los vectores en `R`, va a multiplicar a cada uno de los elementos de la lista por dos. Veámoslo:

In [4]:
# Creemos una lista en Numpy y una copia para poder hacer operaciones con el
# arreglo sin que se me generen modificaciones no deseadas
arreglo = np.arange(0, 10)
operac = arreglo.copy()
operac

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# Multiplicación
operac * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

En efecto, me está tomando cada elemento del arreglo y lo multiplica por dos. No se modifica la cantidad de elementos que contiene mi arreglo. Algo semejante sucederá con las demás operaciones. Entonces, si hago una suma, hará la adición elemento a elemento.

In [6]:
# Suma
operac + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

También podemos hacer operaciones con los elementos correspondientes de dos o más vectores que tienen la misma dimensión.

In [7]:
operac + arreglo

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

## Matrices

Creemos una matriz para que verifiquemos qué sucede:

In [8]:
# Creación de matrices
matriz = arreglo.reshape(2, 5)
matriz_2 = matriz.copy()
matriz_2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

Al hacer operaciones básicas, las hará elemento por elemento, entonces al usar `*`, no hará el producto matricial. Veámoslo:

In [9]:
matriz * matriz_2

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

Para hacer el producto matricial, se debe hacer uso de la función `np.matmul()`.

In [11]:
np.matmul(matriz, matriz_2.T)

array([[ 30,  80],
       [ 80, 255]])

Nótese que se tomó la transpuesta de `matriz_2` para que el número de filas de una matriz coincidiera con el número de columnas de la otra y viceversa. Y se obtiene una matriz $2 \times 2$, ya que la primera matriz tiene dos filas y la segunda matriz tiene dos columnas.